import {
  IconHome,
  IconPoint,
  IconApps,
  IconClipboard,
  IconFileDescription,
  IconBorderAll,
  IconZoomCode,
  IconRotate,
  IconUserPlus,
  IconLogin,
  IconAlertCircle,
  IconSettings,
} from "@tabler/icons-react";
import { nanoid } from "nanoid";

const Menuitems = [
  {
    id: nanoid(10),
    title: "Dashboard",
    icon: IconHome,
    href: "/dashboards/",
    children: [
      {
        id: nanoid(10),
        title: "Modern",
        icon: IconPoint,
        href: "/",
        chipColor: "secondary",
      },
      {
        id: nanoid(10),
        title: "eCommerce",
        icon: IconPoint,
        href: "/dashboards/ecommerce",
      },
    ],
  },
  {
    id: nanoid(10),
    title: "Apps",
    icon: IconApps,
    href: "/apps/",
    children: [
      {
        id: nanoid(10),
        title: "Contacts",
        icon: IconPoint,
        href: "/apps/contacts",
      },
      {
        id: nanoid(10),
        title: "Chats",
        icon: IconPoint,
        href: "/apps/chats",
      },
      {
        id: nanoid(10),
        title: "Notes",
        icon: IconPoint,
        href: "/apps/notes",
      },
      {
        id: nanoid(10),
        title: "Calendar",
        icon: IconPoint,
        href: "/apps/calendar",
      },
      {
        id: nanoid(10),
        title: "Email",
        icon: IconPoint,
        href: "/apps/email",
      },
      {
        id: nanoid(10),
        title: "Tickets",
        icon: IconPoint,
        href: "/apps/tickets",
      },
      {
        id: nanoid(10),
        title: "User Profile",
        icon: IconPoint,
        href: "/user-profile",
        children: [
          {
            id: nanoid(10),
            title: "Profile",
            icon: IconPoint,
            href: "/user-profile",
          },
          {
            id: nanoid(10),
            title: "Followers",
            icon: IconPoint,
            href: "/apps/followers",
          },
          {
            id: nanoid(10),
            title: "Friends",
            icon: IconPoint,
            href: "/apps/friends",
          },
          {
            id: nanoid(10),
            title: "Gallery",
            icon: IconPoint,
            href: "/apps/gallery",
          },
        ],
      },
      {
        id: nanoid(10),
        title: "Ecommerce",
        icon: IconPoint,
        href: "/apps/ecommerce/",
        children: [
          {
            id: nanoid(10),
            title: "Shop",
            icon: IconPoint,
            href: "/apps/ecommerce/shop",
          },
          {
            id: nanoid(10),
            title: "Detail",
            icon: IconPoint,
            href: "/apps/ecommerce/detail/1",
          },
          {
            id: nanoid(10),
            title: "List",
            icon: IconPoint,
            href: "/apps/ecommerce/eco-product-list",
          },
          {
            id: nanoid(10),
            title: "Checkout",
            icon: IconPoint,
            href: "/apps/ecommerce/eco-checkout",
          },
        ],
      },
      {
        id: nanoid(10),
        title: "Blog",
        icon: IconPoint,
        href: "/apps/blog/",
        children: [
          {
            id: nanoid(10),
            title: "Posts",
            icon: IconPoint,
            href: "/apps/blog/posts",
          },
          {
            id: nanoid(10),
            title: "Detail",
            icon: IconPoint,
            href: "/apps/blog/detail/streaming-video-way-before-it-was-cool-go-dark-tomorrow",
          },
        ],
      },
    ],
  },

  {
    id: nanoid(10),
    title: "Pages",
    icon: IconClipboard,
    href: "/ui-components/",
    children: [
      {
        id: nanoid(10),
        title: "Treeview",
        icon: IconPoint,
        href: "/theme-pages/treeview",
      },
      {
        id: nanoid(10),
        title: "Pricing",
        icon: IconPoint,
        href: "/theme-pages/pricing",
      },
      {
        id: nanoid(10),
        title: "Account Setting",
        icon: IconPoint,
        href: "/theme-pages/account-settings",
      },
      {
        id: nanoid(10),
        title: "FAQ",
        icon: IconPoint,
        href: "/theme-pages/faq",
      },
      {
        id: nanoid(10),
        title: "Widgets",
        icon: IconPoint,
        href: "/widgets/cards",
        children: [
          {
            id: nanoid(10),
            title: "Cards",
            icon: IconPoint,
            href: "/widgets/cards",
          },
          {
            id: nanoid(10),
            title: "Banners",
            icon: IconPoint,
            href: "/widgets/banners",
          },
          {
            id: nanoid(10),
            title: "Charts",
            icon: IconPoint,
            href: "/widgets/charts",
          },
        ],
      },
      {
        id: nanoid(10),
        title: "Ui",
        icon: IconPoint,
        href: "/ui-components/alert",
        children: [
          {
            id: nanoid(10),
            title: "Alert",
            icon: IconPoint,
            href: "/ui-components/alert",
          },
          {
            id: nanoid(10),
            title: "Accordion",
            icon: IconPoint,
            href: "/ui-components/accordion",
          },
          {
            id: nanoid(10),
            title: "Avatar",
            icon: IconPoint,
            href: "/ui-components/avatar",
          },
          {
            id: nanoid(10),
            title: "Chip",
            icon: IconPoint,
            href: "/ui-components/chip",
          },
          {
            id: nanoid(10),
            title: "Dialog",
            icon: IconPoint,
            href: "/ui-components/dialog",
          },
          {
            id: nanoid(10),
            title: "List",
            icon: IconPoint,
            href: "/ui-components/list",
          },
          {
            id: nanoid(10),
            title: "Popover",
            icon: IconPoint,
            href: "/ui-components/popover",
          },
          {
            id: nanoid(10),
            title: "Rating",
            icon: IconPoint,
            href: "/ui-components/rating",
          },
          {
            id: nanoid(10),
            title: "Tabs",
            icon: IconPoint,
            href: "/ui-components/tabs",
          },
          {
            id: nanoid(10),
            title: "Tooltip",
            icon: IconPoint,
            href: "/ui-components/tooltip",
          },
          {
            id: nanoid(10),
            title: "Transfer List",
            icon: IconPoint,
            href: "/ui-components/transfer-list",
          },
          {
            id: nanoid(10),
            title: "Typography",
            icon: IconPoint,
            href: "/typography",
          },
        ],
      },
      {
        id: nanoid(10),
        title: "Charts",
        icon: IconPoint,
        href: "/charts/",
        children: [
          {
            id: nanoid(10),
            title: "Line",
            icon: IconPoint,
            href: "/charts/line-chart",
          },
          {
            id: nanoid(10),
            title: "Gredient",
            icon: IconPoint,
            href: "/charts/gredient-chart",
          },
          {
            id: nanoid(10),
            title: "Area",
            icon: IconPoint,
            href: "/charts/area-chart",
          },
          {
            id: nanoid(10),
            title: "Candlestick",
            icon: IconPoint,
            href: "/charts/candlestick-chart",
          },
          {
            id: nanoid(10),
            title: "Column",
            icon: IconPoint,
            href: "/charts/column-chart",
          },
          {
            id: nanoid(10),
            title: "Doughtnut & Pie",
            icon: IconPoint,
            href: "/charts/doughnut-pie-chart",
          },
          {
            id: nanoid(10),
            title: "RadialBar & Radar",
            icon: IconPoint,
            href: "/charts/radialbar-chart",
          },
        ],
      },
      {
        id: nanoid(10),
        title: "Auth",
        icon: IconPoint,
        href: "/400",
        children: [
          {
            id: nanoid(10),
            title: "Error",
            icon: IconAlertCircle,
            href: "/400",
          },
          {
            id: nanoid(10),
            title: "Maintenance",
            icon: IconSettings,
            href: "/auth/maintenance",
          },
          {
            id: nanoid(10),
            title: "Login",
            icon: IconLogin,
            href: "/auth/auth1/login",
            children: [
              {
                id: nanoid(10),
                title: "Side Login",
                icon: IconPoint,
                href: "/auth/auth1/login",
              },
              {
                id: nanoid(10),
                title: "Boxed Login",
                icon: IconPoint,
                href: "auth/auth2/login",
              },
            ],
          },
          {
            id: nanoid(10),
            title: "Register",
            icon: IconUserPlus,
            href: "/auth/auth1/register",
            children: [
              {
                id: nanoid(10),
                title: "Side Register",
                icon: IconPoint,
                href: "/auth/auth1/register",
              },
              {
                id: nanoid(10),
                title: "Boxed Register",
                icon: IconPoint,
                href: "/auth/auth2/register",
              },
            ],
          },
          {
            id: nanoid(10),
            title: "Forgot Password",
            icon: IconRotate,
            href: "/auth/auth1/forgot-password",
            children: [
              {
                id: nanoid(10),
                title: "Side Forgot Password",
                icon: IconPoint,
                href: "/auth/auth1/forgot-password",
              },
              {
                id: nanoid(10),
                title: "Boxed Forgot Password",
                icon: IconPoint,
                href: "/auth/auth2/forgot-password",
              },
            ],
          },
          {
            id: nanoid(10),
            title: "Two Steps",
            icon: IconZoomCode,
            href: "/auth/auth1/two-steps",
            children: [
              {
                id: nanoid(10),
                title: "Side Two Steps",
                icon: IconPoint,
                href: "/auth/auth1/two-steps",
              },
              {
                id: nanoid(10),
                title: "Boxed Two Steps",
                icon: IconPoint,
                href: "/auth/auth2/two-steps",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: nanoid(10),
    title: "Forms",
    icon: IconFileDescription,
    href: "/forms/form-elements/autocomplete",
    children: [
      {
        id: nanoid(10),
        title: "Form Elements",
        icon: IconPoint,
        href: "/forms/form-elements/autocomplete",
        children: [
          {
            id: nanoid(10),
            title: "Autocomplete",
            icon: IconPoint,
            href: "/forms/form-elements/autocomplete",
          },
          {
            id: nanoid(10),
            title: "Button",
            icon: IconPoint,
            href: "/forms/form-elements/button",
          },
          {
            id: nanoid(10),
            title: "Radio",
            icon: IconPoint,
            href: "/forms/form-elements/radio",
          },
          {
            id: nanoid(10),
            title: "Date Time",
            icon: IconPoint,
            href: "/forms/form-elements/date-time",
          },
          {
            id: nanoid(10),
            title: "Slider",
            icon: IconPoint,
            href: "/forms/form-elements/slider",
          },
          {
            id: nanoid(10),
            title: "Switch",
            icon: IconPoint,
            href: "/forms/form-elements/switch",
          },
        ],
      },
      {
        id: nanoid(10),
        title: "Form Layout",
        icon: IconPoint,
        href: "/forms/form-layouts",
      },
      {
        id: nanoid(10),
        title: "Form Horizontal",
        icon: IconPoint,
        href: "/forms/form-horizontal",
      },
      {
        id: nanoid(10),
        title: "Form Vertical",
        icon: IconPoint,
        href: "/forms/form-vertical",
      },
      {
        id: nanoid(10),
        title: "Form Custom",
        icon: IconPoint,
        href: "/forms/form-custom",
      },
      {
        id: nanoid(10),
        title: "Form Wizard",
        icon: IconPoint,
        href: "/forms/form-wizard",
      },
      {
        id: nanoid(10),
        title: "Form Validation",
        icon: IconPoint,
        href: "/forms/form-validation",
      },
    ],
  },
  {
    id: nanoid(10),
    title: "Tables",
    icon: IconBorderAll,
    href: "/tables/",
    children: [
      {
        id: nanoid(10),
        title: "Basic",
        icon: IconPoint,
        href: "/tables/basic",
      },
      {
        id: nanoid(10),
        title: "Collapsible",
        icon: IconPoint,
        href: "/tables/collapsible",
      },
      {
        id: nanoid(10),
        title: "Enhanced",
        icon: IconPoint,
        href: "/tables/enhanced",
      },
      {
        id: nanoid(10),
        title: "Fixed Header",
        icon: IconPoint,
        href: "/tables/fixed-header",
      },
      {
        id: nanoid(10),
        title: "Pagination",
        icon: IconPoint,
        href: "/tables/pagination",
      },
      {
        id: nanoid(10),
        title: "Search",
        icon: IconPoint,
        href: "/tables/search",
      },
    ],
  },
];
export default Menuitems;
